[changelog]
header = """
# Changelog\n
"""
body = """
{% if version -%}
## [{{ version | trim_start_matches(pat="v") }}](https://github.com/jkloning/M9A-Pocket/releases/tag/{{ version }}) - {{ timestamp | date(format="%Y-%m-%d") }}
{% else -%}
## [Unreleased]
{% endif -%}

{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | striptags | trim | upper_first }}
{% for commit in commits %}
- {% if commit.scope %}**{{ commit.scope }}**: {% endif %}{{ commit.message }}
{% endfor %}
{% endfor -%}
"""
trim = true
postprocessors = [
  { pattern = '\((\w+)\)!?:', replace = "**${1}**:" },
]

[git]
conventional_commits = true
filter_unconventional = false
split_commits = false
commit_parsers = [
  { message = "^feat", group = "<!-- 0 -->✨ 新增 | Features" },
  { message = "^fix", group = "<!-- 1 -->🐛 修复 | Bug Fixes" },
  { message = "^perf", group = "<!-- 2 -->⚡ 优化 | Performance" },
  { message = "^refactor|^rft", group = "<!-- 3 -->♻️ 重构 | Refactor" },
  { message = "^docs|^doc", group = "<!-- 4 -->📝 文档 | Documentation" },
  { message = "^style", group = "<!-- 5 -->💄 样式 | Styling" },
  { message = "^test", group = "<!-- 6 -->✅ 测试 | Testing" },
  { message = "^chore", group = "<!-- 7 -->🔧 杂项 | Miscellaneous" },
  { message = "^ci|^build", skip = true },
  { message = "^Merge", skip = true },
  { message = ".*", group = "<!-- 99 -->📦 其他 | Other" },
]
protect_breaking_commits = false
filter_commits = false
tag_pattern = "v[0-9].*"
sort_commits = "newest"
